baseURL = "https://yourgithubusername.github.io/"
languageCode = "en-us"
title = "Blog-OS"
theme = "PaperMod"


[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
  identifier = "archives"
  name = "Archives"
  url = "/archives/"
  weight = 30

  [[menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 10
  
  
  [[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 20

  
[params]
  ShowReadingTime = true
  ShowToc = true
  TocOpen = true
  ShowRssButtonInSectionTermList = true
  ShowShareButtons= true

  [params.profileMode]
    enabled = false  # Disable profile mode

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]
